### ISSUE TITLE
SFC detection: React 16

### ISSUE THREAD

**Issue by ljharb** [jsx-eslint/eslint-plugin-react#1510]
Prior to React 16, separate from what detection rules are actually in the code, an SFC conceptually meets the following static criteria:
 - a function
 - name starts with a capital letter if not stored on an object property
 - returns JSX, or returns `null`
 - takes no more than two arguments (`props` and `context`, destructured or otherwise)
 - has any of the following static properties: `propTypes`, `defaultProps`, `contextTypes`, `displayName`
 - if it's used anywhere in the current file in a createElement/jsx context

In React 16, components can also return strings, and/or arrays.

This issue is to track:
 - [ ] updating our SFC detection to meet the above pre-16 criteria, if needed
 - [ ] updating our SFC detection, when the React version pragma is "16", to handle SFCs returning fragments.

**Comment by petersendidit** [comment]
While looking at how to implement this here is some thoughts I had.

Right now `getParentStatelessComponent` only verifies a few of the items above. It doesn't verify the name of the component starts with a capital letter nor does it check if it returns JSX or the number of arguments.... It's not as simple as updating `getParentStatelessComponent` to handle those cases because we have rules that are depending on `getParentStatelessComponent` finding "components" that don't match all the rules.

Example being the display name rule wanting to find this as a component and making it invalid because it doesn't have a display name.
```js
import React, { createElement } from "react";
export default (props) => {
  return createElement("div", {}, "hello");
};
```

Right now the `Components` util stores its confidence of the node being a component `(0=banned, 1=maybe, 2=yes)` but the `list` method on `Components` doesn't have a way to ask for "maybe" components.

We might have to define what of those above rules are required to be a "maybe" component, update `list` to be able to return both "maybe" and "yes" components on request and then update the rules to ask for the both when needed.

**Comment by ardok** [comment]
I seem to hit this issue: `react/no-this-in-sfc` for a method inside a component that extends another component.

```
class Foo extends React.Component<{show: boolean}> {
  renderTable = () => {
    const {show} = this.props;
    if (!show) {
      return null;
    }
    return <div>table</div>;
  };

  render() {
    return this.renderTable();
  }
}

class Bar extends Foo {
  renderTable = () => {
    const {show} = this.props;  // react/no-this-in-sfc error
    if (!show) {
      return null;
    }
    return <div>something else</div>;
  };
}
```

**Comment by ljharb** [comment]
@ardok in react, components should never extend other components. Prefer composition over inheritance.

**Comment by ljharb** [comment]
@ardok there's no way to statically know it's a component if it's not directly extending React.Component - but you can use an "extends" comment to note it - see https://github.com/yannickcr/eslint-plugin-react/issues/1856#issuecomment-400458910

**Comment by Maxim-Mazurok** [comment]
> SFC is deprecated as of recent React versions, function components can no longer be considered 'stateless'. Please use `FunctionComponent` instead.
https://stackoverflow.com/questions/53885993/react-16-7-react-sfc-is-now-deprecated

So, probably now we need a rule to bad SFC.

**Comment by ljharb** [comment]
That's a TS type; the community-used term isn't bannable and isn't up to the React team.

**Comment by ljharb** [comment]
I think this is largely resolved; please open new issues if there's any further problems with SFC component detection.
