### ISSUE TITLE
Add Rule option "disallowedFor" for component prop

### ISSUE THREAD

**Issue by jacketwpbb** [jsx-eslint/eslint-plugin-react#3422]
Suppose we have a component that accept a prop named string.

``` javascript
function Comp(props) {
    return <div>{props.string}</div>;
}

function App() {
    return <Comp string="213"  />;
}

```

As needs change, we need to replace string prop by another named number.

``` javascript

function Comp(props) {
    return <div>{props.number || props.string}</div>;
}
Comp.propTypes = {
    number: PropTypes.number,
    /**
     * @deprecated use number instead
     */
    string: PropTypes.string
};
Comp.defaultProps = {
    string: '123',
    number: 123
};
```

The string prop will works in a period of time, but it's better to replace it with number prop.
This rule option can be use to avoid using deprecated prop for Comp.

``` json
{
"react/forbid-component-props": [
    "error", { "forbid": [{"propName": "string", "disallowedList": ["Comp"]}] }
  ]
}

```
![image](https://user-images.githubusercontent.com/19347280/189034303-da35ea57-1f86-4cb0-bc51-a406ed5bbb69.png)

**Comment by ljharb** [comment]
Since it's marked as deprecated with jsdoc, there's `eslint-plugin-deprecated` - and if you're using TS, it will catch it too.

Why can't you just remove it and make a major bump?

**Comment by cincodenada** [comment]
Hello, I would also like this: my use case is for discouraging the usage of props in components that I don't control, and thus can't annotate or use the component myself.

I could wrap it in an HOC and use that instead, but that doesn't prevent others from using the original component, so it doesn't really get me very far. I also don't want to create and HOC and than ban the original altogether, because that would be a much larger change for not a lot of benefit.

**Comment by ljharb** [comment]
@cincodenada you can prevent them from using the original component using `no-restricted-imports` and/or `no-restricted-properties`, fwiw.

That said, thanks, that is a reasonable use case.
