### ISSUE TITLE
Rule proposal: flagging useEffect+useState used instead of variable

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [jsx-eslint/eslint-plugin-react#3446]
Folks new to hooks sometimes write a combination of `useEffect` and `useState` to initialize a value:

```js
const [value, setValue] = useState();

useEffect(() => {
    setValue(computeValue());
}, []);
```

Oftentimes it's simpler to use a variable with an immediately available value:

```js
const value = computeValue();
```

...or, if the computation is expensive, use `useMemo`:

```js
const value = useMemo(() => computeValue(), []);
```

Proposal: let's make a rule that flags direct instances of this antipattern? It could have two _suggestion_ fixers based on the two alternatives.

**Comment by ljharb** [comment]
This doesn’t seem very common, and these suggestions would actually risk breakage if the computation required the DOM (since that’s also what useEffect is for), and it’s pretty critical that components not be encouraged to break server rendering use cases.

Either way, hook-specific rules likely belong in eslint-plugin-react-hooks.
